version: "3"

services:
  hadoop-master:
    build: .
    container_name: hadoop-master
    hostname: hadoop-master
    depends_on:
      - hadoop-worker1
      - hadoop-worker2
    ports:
      - 9870:9870
      - 8088:8088
      - 7077:7077
      - 9092:9092
      - 16010:16010
    networks:
      - hadoop
    volumes:
      - ./:/app
  hadoop-worker1:
    image: ranimmbarek/hadoop-cluster
    hostname: hadoop-worker1
    ports:
      - 8040:8042
    networks:
      - hadoop
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  hadoop-worker2:
    hostname: hadoop-worker2
    image: ranimmbarek/hadoop-cluster
    ports:
      - 8041:8042
    networks:
      - hadoop
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - hadoop
    depends_on:
      - cassandra
    volumes:
      - grafana-storage:/var/lib/grafana
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    networks:
      - hadoop
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra

volumes:
  grafana-storage:

networks:
  hadoop:
    driver: bridge